server:
  port: 18093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.75.134
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.75.131
    virtual-host: /fengge
    username: fengge
    password: fengge
    publisher-confirm-type: CORRELATED
    publisher-returns: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.136:3306/guli_payment
    username: zc
    password: 123456
feign:
  sentinel:
    enabled: true
alipay:
  gatewayUrl: https://openapi.alipay.com//gateway.do
  app_id: 2021001163617452
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8Z7EZmanxyFGsK4LrIUeKKrrGxWAHIgPmUV8TtZDs+jeplJSw1ckSY63QhEU444D5qd6xruJHBuB33HG+ik4n8N8nRW
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkWs+3gXMosiWG+EbfRyotWB0waqU3t7qMQSBxU0r3JZoND53jvWQfzrGZ8W+obMc+OgwupODDVxhG/DEKVBIptuUQYdvAjCSH9
  notify_url: http://wh399wlif0.54http.tech/pay/success
  return_url: http://wh399wlif0.54http.tech/pay/ok
