server:
  port: 18093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.75.134
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.75.131
    virtual-host: /fengge
    username: fengge
    password: fengge
    publisher-confirm-type: CORRELATED
    publisher-returns: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.136:3306/guli_payment
    username: zc
    password: 123456
feign:
  sentinel:
    enabled: true
